### ISSUE TITLE
Another script for another version

### ISSUE THREAD

**Issue by jwilderm** [geometalab/HSRVote_XML-Converter#5]
Python2 and Python3 are too different. There should be 2 different scripts for both versions.

**Comment by sfkeller** [comment]
Ok. Let's prefer 3 and implement just for 3.

**Comment by das-g** [comment]
> Ok. Let's prefer 3 and implement just for 3.

Indeed, let's not care about Python 2 compatibility [when there are less than 3 month left](https://pythonclock.org/) until Python 2's official end-of-life.

All new Python software should be written for Python 3 (and is allowed to be Python-3-only, without any support for Python 2).
